### ISSUE TITLE
sp.download method giving Error

### ISSUE THREAD

**Issue by dijeasakura** [chanon-kr/Shared_Function#3]
Hii, 

I need help to download my excel file in sharepoint, i already followed your tutorial

and i stuck when downloading the file, thank you so much

```
sp = lazy_SP365(site_url = 'site url'
                   , client_id = 'client_id'
                   , client_secret = 'secret')
# Authen OK

download_path = sp.create_link('my link from the copied link sharepoint')

sp.download(sharepoint_location = download_path 
            , local_location = 'C:/data/sharepoint.xlsx')
```

and it gives me this error

Exception: Cannot Download File
Return with error code : 400
Content of error : b'{"error":{"code":"-2147024809, System.ArgumentException","message":{"lang":"en-US","value":"Server relative urls must start with SPWeb.ServerRelativeUrl"}}}'

**Comment by chanon-kr** [comment]
Hi, I want to know more details, so, I can try to reproduce your case.

Let use fake names like these ;

1. your site's name is 'abc'
2. your organze is 'xyz'.
3. your channel is 'General'
4. your file name is 'file_name.xlsx'

From those names, I have 2 questions.

1. Is your "site_url" look like this? >> "https://xyz.sharepoint.com/sites/abc"

2. Is the file's link look like this >> "https://xyz.sharepoint.com/:p:/r/sites/abc/Shared%20Documents/General/file_name.xlsx?bahvbahbahfoqe;ghqegqg"

3. And is the "download_path" that "sp.create_link" created from 2. look like this? >> "/sites/abc/Shared%20Documents/General/file_name.xlsx"

**Comment by dijeasakura** [comment]
Thanks for your reply, I Hope this information can help you

1. my site_url = 'https://xyz-my.sharepoint.com/personal/abc'
2. file_link = 'https://xyz.sharepoint.com/:x:/s/xxx-data/BALJ9gA44_aBcdFg7VkiMbkC8oiI9KKX_I_8pmYsdJIOWw?e=mgmgBb
3. '/siteshttps://xyz.sharepoint.com/:x:/s/xxx-data/BALJ9gA44_aBcdFg7VkiMbkC8oiI9KKX_I_8pmYsdJIOWw'

for number 3 i already try manually using this 
'/sites/https://xyz.sharepoint.com/:x:/s/xxx-data/BALJ9gA44_aBcdFg7VkiMbkC8oiI9KKX_I_8pmYsdJIOWw'

**Comment by chanon-kr** [comment]
Oh, my bad, this is the first time that I encounter with a personal sharepoint.

I think the problem here is the 'download_path' from 'sp.create_link' which I made it specifically for sharepoint site.
As you can see that the 'download_path ' you got from personal sharepoint is really messed up.

I will try to do download file with my personal sharepoint with this lazy_SP365.

While waiting for my test result, if you really need a quick measure.
You can try this lazy_SP365 by create a dummy sharepoint site and download file from it.
*The easiest way is creating the MS team's team and the sharepoint site will be created.

**Comment by chanon-kr** [comment]
Solved it faster than I thought =_="

To make it work, let use fake names like these ;

1. your url is something like >> "https://xyz-my.sharepoint.com/personal/abc"
2. your file name >> "file_name.xlsx"
3. your file is in folder >> "My files > FolderA1"

Then your parameter is like these.
- "site_url" = "https://xyz-my.sharepoint.com/personal/abc"
- "download_path" = "/personal/abc/Documents/FolderA1/file_name.xlsx"

Please try and inform me if it is work for you or not, thanks!!

**Comment by dijeasakura** [comment]
Thanks it works for the personal file

But can it work for shared document /file?

Really appreciate your help

**Comment by chanon-kr** [comment]
Oh, that's great!!

About shared document, what kind of scenario is that?
Somebody shares file to you, or you share to somebody?

**Comment by dijeasakura** [comment]
Yes, somebody shared the file with me (i can edit and do anything)

**Comment by chanon-kr** [comment]
Umm, interesting question, to test, I have to ask my friend to share a file with me maybe they can do that on Monday or Tuesday.

By the way, can you access that shared file from your personal sharepoint?
I mean from "https://xyz-my.sharepoint.com/personal/abc/XXXXXX".

If you can access from that url, I think you should be able to download with this lazy_SP365.

**Comment by dijeasakura** [comment]
I think when i open the shared excel file the file link will become like this

file_link =https://xyz.sharepoint.com/:x:/s/folder-name/BALJ9gA44_aBcdFg7VkiMbkC8oiI9KKX_I_8pmYsdJIOWw?e=mgmgBb

**Comment by chanon-kr** [comment]
I just tested, because the shared file's link was

https://xyz-my.sharepoint.com/personal/myfriend/............

So, I can't download because the file wasn't in my site's URL.

In order to make this method available with shared file from your friend, I think you need to config authentication with your friend's personal site, too.

**Comment by dijeasakura** [comment]
Yes, i just tested and it worked

So i need to setup another client ID on the owner sharepoint

Thanks for your help, really appreciated

**Comment by chanon-kr** [comment]
You're welcome, I also learn something from you.
